apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - inference-service.yaml

patches:
  - target:
      kind: PodMonitor
      name: vllm-monitor
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/serving.kserve.io~1inferenceservice
        value: "gpt-oss-20b-vllm"
  - target:
      kind: Service
      name: vllm-lb
    patch: |-
      - op: replace
        path: /spec/selector/app
        value: "isvc.gpt-oss-20b-predictor"