apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-llm

resources:
  - guidellm-job.yaml

configMapGenerator:
  - name: guidellm-data
    files:
      - shared-prefix-data.jsonl
    options:
      disableNameSuffixHash: true
